apiVersion: apps/v1
kind: Deployment
metadata:
  name: fi-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fi
  template:
    metadata:
      labels:
        app: fi
    spec:
      containers:
        - name: fi
          image: haridalavai/fi-linklab
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: fi-srv
spec:
  selector:
    app: fi
  ports:
    - name: fi
      protocol: TCP
      port: 3000
      targetPort: 3000
